name: Flask App CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask pytest requests
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Run Unit Tests
      run: |
        python -m pytest test_app.py -v
    
    - name: Start Flask App
      run: |
        python app.py &
        sleep 5
      
    - name: Run Integration Tests
      run: |
        python -m pytest integration_test.py -v